version: "3.8"

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    hostname: proxy
    volumes:
      - ./static:/usr/share/nginx/html:ro
    ports:
      - 3006:80

  clickhouse:
    build:
      context: ./clickhouse-config
      dockerfile: Dockerfile
    user: 101:101
    ports:
      - "0.0.0.0:8123:8123" # HTTP interface - access /play for testing
      - "0.0.0.0:9000:9000" # Native interface
    container_name: clickhouse
    hostname: clickhouse
    env_file:
      - .env
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - clickhouse_users:/etc/clickhouse-server/users.d/
      - ./clickhouse-logs:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8123/ping",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9001:9001 # S3 API
      - 9002:9002 # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_CORS_ALLOW_ORIGIN: "http://localhost:3000,http://localhost:3006,*"
    volumes:
      - minio_data:/data
    command: server /data --address ":9001" --console-address ":9002"

  minio-cors:
    image: amazon/aws-cli:latest
    container_name: minio-cors
    depends_on:
      - minio
    restart: "no"
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - ./minio-config/cors.json:/config/cors.json:ro
    entrypoint: ["/bin/sh", "-c"]
    command: >
      set -euo pipefail;
      until aws --endpoint-url http://minio:9001 s3 ls >/dev/null 2>&1; do
        echo "waiting for minio..."; sleep 2;
      done;
      aws --endpoint-url http://minio:9001 s3api create-bucket --bucket betterlytics-replays || true;
      aws --endpoint-url http://minio:9001 s3api put-bucket-cors --bucket betterlytics-replays --cors-configuration file:///config/cors.json;
      echo "Applied bucket CORS for betterlytics-replays";

volumes:
  clickhouse_data:
  clickhouse_users:
  postgres_data:
  minio_data:
