version: "3.8"

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    hostname: proxy
    volumes:
      - ./static:/usr/share/nginx/html:ro
    ports:
      - 3006:80

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    user: 101:101
    ports:
      - "0.0.0.0:8123:8123" # HTTP interface - access /play for testing
      - "0.0.0.0:9000:9000" # Native interface
    container_name: clickhouse
    hostname: clickhouse
    env_file:
      - .env
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - clickhouse_users:/etc/clickhouse-server/users.d/
      - ./clickhouse-logs:/var/log/clickhouse-server/
      - ./clickhouse-config/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse-config/setup/:/docker-entrypoint-initdb.d/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  clickhouse_data:
  clickhouse_users:
  postgres_data:
