version: "3.8"

services:
  static:
    image: nginx:alpine
    container_name: static
    hostname: static
    volumes:
      - ./static:/usr/share/nginx/html:ro
    ports:
      - 3006:80

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend
    hostname: backend
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env.production
    depends_on:
      init:
        condition: service_completed_successfully

  dashboard:
    build:
      context: ./better-analytics-dashboard
      dockerfile: ./Dockerfile
    env_file:
      - ./better-analytics-dashboard/.env.production
    ports:
      - 3000:3000
    depends_on:
      init:
        condition: service_completed_successfully

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    user: 101:101
    ports:
      - "0.0.0.0:8123:8123" # HTTP interface - access /play for testing
      - "0.0.0.0:9000:9000" # Native interface
    container_name: clickhouse
    hostname: clickhouse
    env_file:
      - .env.production
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - ./clickhouse-logs:/var/log/clickhouse-server/
      - ./clickhouse-config/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse-config/setup/:/docker-entrypoint-initdb.d/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

  init:
    image: node:20-alpine
    container_name: init
    hostname: init
    env_file:
      - .env.production
      - ./better-analytics-dashboard/.env.production
    volumes:
      - ./package.json:/app/package.json:ro
      - ./migrations:/app/migrations:ro
      - ./scripts:/app/scripts:ro
      - ./better-analytics-dashboard/package.json:/app/better-analytics-dashboard/package.json:ro
      - ./better-analytics-dashboard/prisma:/app/better-analytics-dashboard/prisma:ro
    command:
      - /bin/sh
      - -c
      - |
        cd /app
        npm install
        npm run prod-migrate
        cd ./better-analytics-dashboard
        npm install
        npx prisma@6.8.2 migrate deploy
        npx prisma@6.8.2 db seed
    depends_on:
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  clickhouse_data:
  postgres_data:
