version: "3.8"

services:
  static:
    image: nginx:alpine
    container_name: static
    hostname: static
    volumes:
      - ./static:/usr/share/nginx/html:ro
    ports:
      - 3006:80

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    depends_on:
      ba_init:
        condition: service_completed_successfully

  dashboard:
    build:
      context: ./better-analytics-dashboard
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      ba_init:
        condition: service_completed_successfully

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    user: 101:101
    ports:
      - "0.0.0.0:8123:8123" # HTTP interface - access /play for testing
      - "0.0.0.0:9000:9000" # Native interface
    container_name: clickhouse
    hostname: clickhouse
    env_file:
      - .env
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - ./clickhouse-logs:/var/log/clickhouse-server/
      - ./clickhouse-config/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse-config/setup/:/docker-entrypoint-initdb.d/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

  ba_init:
    image: alpine:3.20
    container_name: ba_init
    env_file:
      - .env
    depends_on:
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
    command:
      - /bin/sh
      - -c
      - |
        cd /usr/src/app
        wget -qO- https://get.pnpm.io/install.sh | sh -
        pnpm run migrate
        pnpm run seed

volumes:
  clickhouse_data:
  postgres_data:
