packages:
  - backend
  - dashboard
  - docs

overrides:
  tough-cookie@<4.1.3: '>=4.1.3'
  mermaid@>=11.1.0 <11.10.0: '>=11.10.0'
  mermaid@>=11.0.0-alpha.1 <11.10.0: '>=11.10.0'
  next-auth@<4.24.12: '>=4.24.12'
  form-data@<2.5.4: '>=2.5.4'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  qs@<6.14.1: '>=6.14.1'
