global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "rust-backend"
    static_configs:
      - targets: ["host.docker.internal:3001"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "nextjs-dashboard"
    static_configs:
      - targets: ["host.docker.internal:3000"]
    metrics_path: "/api/metrics"
    scrape_interval: 5s
