import { z } from "zod";

const RESERVED_SLUGS = ["feed.xml", "index", "tag", "tags", "archive", "page"];

export const blogFrontmatterSchema = z.object({
  title: z.string().min(10).max(80),
  description: z.string().min(50).max(160),
  blueWord: z.string().min(1).optional(),
  slug: z
    .string()
    .regex(/^[a-z0-9-]+$/)
    .refine((s) => !RESERVED_SLUGS.includes(s), "reserved slug"),
  publishedAt: z.string().datetime(),
  updatedAt: z.string().datetime().optional(),
  author: z.string(),
  tags: z.array(z.string()).max(6).default([]),
  // A real photo. Optional — posts without one get a procedural cover
  // generated by /docs-static/api/blog/cover (configured via `cover` below).
  coverImage: z
    .object({
      src: z.string(),
      alt: z.string(),
      width: z.number().int().positive(),
      height: z.number().int().positive(),
    })
    .optional(),
  // Procedural cover config (only used when there's no `coverImage`). Everything
  // is optional: omit it entirely and the post still gets a deterministic cover
  // (texture picked from the slug hash, seed from the slug). Pin any field to
  // lock the look forever.
  cover: z
    .object({
      texture: z.enum(["smoothed-ca", "flow", "voronoi"]).optional(),
      seed: z.number().int().optional(),
      palette: z.enum(["blue", "neutral"]).optional(),
      contrast: z.number().positive().optional(),
      blur: z.number().nonnegative().optional(),
      params: z.record(z.string(), z.number()).optional(),
    })
    .optional(),
  ogImage: z.string().optional(),
  draft: z.boolean().default(false),
  featured: z.boolean().default(false),
  keywords: z.array(z.string()).min(3).max(15),
  faqs: z.array(z.object({ q: z.string(), a: z.string() })).default([]),
  citations: z
    .array(z.object({ label: z.string(), url: z.string().url() }))
    .default([]),
});

export type BlogFrontmatter = z.infer<typeof blogFrontmatterSchema>;
